# Workflow
# Should Have Name
name: Hello
# On tells when the workflow should run
on:
  workflow_dispatch: 
# Jobs
#should be inside the workflow
# Job tells what the workflow should do
jobs:
  say-hello:
    runs-on: ubuntu-latest     #creats an Ephermal container with ubuntu running
    steps:
      - name: Say hello to everyone
        run: echo "Hello-dosto"
# Steps
#should be inside the job

# Actions
# should be inside the steps
